# commit to be tagged for the new release
commit = "HEAD"

project_name = "sbc-raspberrypi"
github_repo = "siderolabs/sbc-raspberrypi"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.5"
pre_release = false

# [notes]
